language: node_js
node_js: '8'
script:
- yarn lint
- yarn test
- yarn prettier-check
- NODE_ENV=development yarn build
- NODE_ENV=production yarn build
before_deploy: ls -al dist
deploy:
  provider: npm
  email: opensource@ekino.com
  skip_cleanup: true
  api_key:
    secure: Nkd3P4tb9PFu8yGzLX1QXt6DP10pfabVUVV506CuqTZzeey03I1xhlEUjWKA7UJuiH+Bvm7oDOpNN5AAmDS/ILpKjxluBvsjMri9/+e7Xil53dFy2l0+LZ7JyE1yiVTrZjDP87CGKLRZ3Q4vW2WeDqJ6CGSguXl7GVlnzsqeaIy4K894wKGXfk0tGWPJRQRbf8NjRMenyUCZT+19pS5DLJRGis8TVk8D4E6XDjZzFT+A5WqJlEedsRC3DyJCnoBrU/NF57mve1bMwsK4JFGgEvT+KYNZB0c9/voYWSix7UO5iaHgQTtuCxvLKnJmKdpuGleWOkSiN7LZd46d/TfDXk2rrbdCnOOvqSVNBCx3ekkXurPAfUdsfSvhjuVhHzeFYP+Xtt5g0jBqzpYzRNocSXHJj75Plg/kc5+SPKzbKLr93AOVsZSfvlcQDqHDeY9xVdIcJjOzplRYJ/6xxW/VKmUvg+spItQGPJRqqUU32+6YXAEl5c+pI6oTLDCw9uR7iry604+blqJwk6OsxtYAmyJUihiv2viFq7AZR6rTAdeeBrNwNtKK0nKyKvisKtoNTID7AIfINSfL+yn336nl5JucMMb2SAAjqB3/O5+z5DHaX5tGZZ8fUfJEh/KP2URAhu3GD0jYHiICb4oTrPCw1bul2icipL19GAAjOGC44hw=
  on:
    tags: true
    repo: ekino/autodata
