language: node_js

node_js:
  "6"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint
  - yarn test
  - NODE_ENV=development yarn build
  - NODE_ENV=production yarn build

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: ekino/autodata
